import floor from "../assets/images/parking.png";
import { IParkingDetail } from "../pages/bookSpaces/types/bookSpace";

const getParkingSlots = async () => {
  const base64data: string | ArrayBuffer | null = await fetch(floor.src)
    .then((response) => response.blob())
    .then((blob) => {
      const reader = new FileReader();
      reader.readAsDataURL(blob);
      return new Promise((res) => {
        reader.onloadend = () => {
          res(reader.result);
        };
      });
    });
  const parkingDetails: IParkingDetail = {
    floorDetails: [
      {
        floorName: "Ground Floor",
        floorId: "1",
        parkingSlots: [
          {
            top: "40px",
            left: "122px",
            isAvailable: true,
            id: "Slot -1",
            name: "Robert Mathew",
          },
          {
            top: "40px",
            left: "159px",
            isAvailable: true,
            id: "Slot -2",
            name: "James Rodrigues",
          },
          {
            top: "40px",
            left: "191px",
            isAvailable: true,
            id: "Slot -3",
            name: "John David",
          },
          {
            top: "40px",
            left: "228px",
            isAvailable: true,
            id: "Slot -4",
            name: "Williams Edward",
          },
          {
            top: "40px",
            left: "256px",
            isAvailable: true,
            id: "Slot -5",
            name: "Williams Edward",
          },
          {
            top: "40px",
            left: "285px",
            isAvailable: true,
            id: "Slot -6",
            name: "Williams Edward",
          },
          {
            top: "40px",
            left: "324px",
            isAvailable: true,
            id: "Slot -7",
            name: "Williams Edward",
          },
          {
            top: "40px",
            left: "356px",
            isAvailable: true,
            id: "Slot -8",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "159px",
            isAvailable: true,
            id: "Slot -9",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "191px",
            isAvailable: true,
            id: "Slot -10",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "228px",
            isAvailable: true,
            id: "Slot -11",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "256px",
            isAvailable: true,
            id: "Slot -12",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "286px",
            isAvailable: true,
            id: "Slot -13",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "323px",
            isAvailable: true,
            id: "Slot -14",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "356px",
            isAvailable: true,
            id: "Slot -15",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "394px",
            isAvailable: true,
            id: "Slot -16",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "427px",
            isAvailable: true,
            id: "Slot -17",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "466px",
            isAvailable: true,
            id: "Slot -18",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "498px",
            isAvailable: true,
            id: "Slot -19",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "123px",
            isAvailable: true,
            id: "Slot -20",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "159px",
            isAvailable: true,
            id: "Slot -21",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "192px",
            isAvailable: true,
            id: "Slot -22",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "227px",
            isAvailable: true,
            id: "Slot -23",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "257px",
            isAvailable: true,
            id: "Slot -24",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "285px",
            isAvailable: true,
            id: "Slot -25",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "323px",
            isAvailable: true,
            id: "Slot -26",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "356px",
            isAvailable: true,
            id: "Slot -27",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "394px",
            isAvailable: true,
            id: "Slot -28",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "427px",
            isAvailable: true,
            id: "Slot -29",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "466px",
            isAvailable: true,
            id: "Slot -30",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "498px",
            isAvailable: true,
            id: "Slot -8",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "536px",
            isAvailable: true,
            id: "Slot -8",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "566px",
            isAvailable: true,
            id: "Slot -8",
            name: "Williams Edward",
          },
        ],
        imageData: base64data,
      },
      {
        floorName: "First Floor",
        floorId: "2",
        parkingSlots: [
          {
            top: "40px",
            left: "122px",
            isAvailable: true,
            id: "Slot -1",
            name: "Robert Mathew",
          },
          {
            top: "40px",
            left: "159px",
            isAvailable: true,
            id: "Slot -2",
            name: "James Rodrigues",
          },
          {
            top: "40px",
            left: "191px",
            isAvailable: true,
            id: "Slot -3",
            name: "John David",
          },
          {
            top: "40px",
            left: "228px",
            isAvailable: true,
            id: "Slot -4",
            name: "Williams Edward",
          },
          {
            top: "40px",
            left: "256px",
            isAvailable: true,
            id: "Slot -5",
            name: "Williams Edward",
          },
          {
            top: "40px",
            left: "285px",
            isAvailable: true,
            id: "Slot -6",
            name: "Williams Edward",
          },
          {
            top: "40px",
            left: "324px",
            isAvailable: true,
            id: "Slot -7",
            name: "Williams Edward",
          },
          {
            top: "40px",
            left: "356px",
            isAvailable: true,
            id: "Slot -8",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "159px",
            isAvailable: true,
            id: "Slot -9",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "191px",
            isAvailable: true,
            id: "Slot -10",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "228px",
            isAvailable: true,
            id: "Slot -11",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "256px",
            isAvailable: true,
            id: "Slot -12",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "286px",
            isAvailable: true,
            id: "Slot -13",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "323px",
            isAvailable: true,
            id: "Slot -14",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "356px",
            isAvailable: true,
            id: "Slot -15",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "394px",
            isAvailable: true,
            id: "Slot -16",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "427px",
            isAvailable: true,
            id: "Slot -17",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "466px",
            isAvailable: true,
            id: "Slot -18",
            name: "Williams Edward",
          },
          {
            top: "187px",
            left: "498px",
            isAvailable: true,
            id: "Slot -19",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "123px",
            isAvailable: true,
            id: "Slot -20",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "159px",
            isAvailable: true,
            id: "Slot -21",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "192px",
            isAvailable: true,
            id: "Slot -22",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "227px",
            isAvailable: true,
            id: "Slot -23",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "257px",
            isAvailable: true,
            id: "Slot -24",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "285px",
            isAvailable: true,
            id: "Slot -25",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "323px",
            isAvailable: true,
            id: "Slot -26",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "356px",
            isAvailable: true,
            id: "Slot -27",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "394px",
            isAvailable: true,
            id: "Slot -28",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "427px",
            isAvailable: true,
            id: "Slot -29",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "466px",
            isAvailable: true,
            id: "Slot -30",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "498px",
            isAvailable: true,
            id: "Slot -8",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "536px",
            isAvailable: true,
            id: "Slot -8",
            name: "Williams Edward",
          },
          {
            top: "315px",
            left: "566px",
            isAvailable: true,
            id: "Slot -8",
            name: "Williams Edward",
          },
        ],
        imageData: base64data,
      },
    ],
  };
  return parkingDetails;
};
const saveSlot = (slotId) => {
  //save this to db
};

const ParkingService = {
  getParkingSlots,
  saveSlot,
};

export default ParkingService;
