export type MyBookingsType = {
  id: string;
  title: string;
  meetingRoomName: string;
  date: Date;
  fromTime: Date;
  toTime: Date;
  amenities: Record<string, boolean>[];
};

// Generated by https://quicktype.io

export interface BookingDetailsNew {
  id: string;
  date: Date;
  meetingRoomName: string;
  title: string;
  fromTime: Date;
  toTime: Date;
  image: string;
  amenities: Amenity[];
}

export interface Amenity {
  Projector: boolean;
  Whiteboard: boolean;
  Wifi: boolean;
  "Video Conferencing": boolean;
  Speaker: boolean;
  Microphone: boolean;
  TV: boolean;
  Telephone: boolean;
}
